export const data = [
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzUfQ8GDTD7ub8ictkguYlYS-0lErBQdJYog&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLhrj_nRybqRs--_aXsOgwTz8PveTTdt_CVA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhRbrbyxiEwJml8H2oXB5UL3E7Me4ZebBf3DoYNGk5RVj0P0TnQ5Hf6HJz-IVchIEyHc8&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv3ALFuRXIAcdGJ6na4pHVgHqd7-Xjkgrl3w&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQynWU_TVIrJy8hkV0J-C6if7iSC3fbuk1crDEMTrRIMmuqTmGlf5J3dSpSSAwdbNFO_38&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuYrLDJAD3RBKOWh1f4cC8sLNGxMd6K_VQDw&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiAsQCAIkcsgKDWDpqihB2bzIsyfxUnLQUog&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsOsVrOcN7pQhUrNlzCa6WOg9K9siPyTbwiw&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoElfe-j7IMKr-Axj2-LzPLyrJEGMoRgojDA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_eNUC7BRwHHoRKYdN3AYR_h2fvSNXrOaWJQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtCU0qmpMbKcamy14MbargZYsOzd8CSYkDQw&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq9la1KLWmUkxBlFjdThYPeztkMjHch4dEMg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyIDgtNXh7-W9SSVlKbAbA1v1-nBS6lsDffA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMPNOUaG0hxWkqcu8w3LVQxyYtFkn3wB_Qlw&usqp=CAU",
];
